# Generated by Django 3.2.9 on 2021-12-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_coursemodule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodule',
            old_name='Course',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(upload_to='course'),
        ),
    ]
