# Generated by Django 4.0.1 on 2022-01-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_subject_subject_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
